Merge #1331: [Core] CheckColdStakeFreeOutput: skip SPORK checks if mnsync incomplete
bd6248187f58141027798bbec2843724ee18ab2f [Core] CheckColdStakeFreeOutput: skip SPORK checks if mnsync incomplete (random-zebra)

Pull request description:

  Currently `CheckBlock` skips the masternode (or budget) payment check in coinstakes when `IsInitialBlockDownload()` returns true (essentially when the current best block time is older than nMaxTipAge seconds).

  Since, in order to verify the block payee, the masternode list needs to be up to date, `IsBlockPayeeValid`also skips the checks when mnsync has not finished.
  `CheckColdStakeFreeOutput` however, does not, so, when the spork list is not updated, SPORK_13 and SPORK_9 cannot be verified (in case of budget payment blocks) resulting in CheckBlock failures with
  ```
  ERROR: CheckColdStakeFreeOutput: Wrong cold staking outputs:
  ```
  (Unless the user doesn't manually set a lower nMaxTipAge to force IsInitialBlockDownload to true).

  This fixes it.

ACKs for top commit:
  Fuzzbawls:
    utACK bd6248187f58141027798bbec2843724ee18ab2f
  furszy:
    utACK bd62481

Tree-SHA512: aa52ac0c9bc597d7bceec88924fd6f264aa3588915eb1052dd28f32e133d16d2ab6527a67ef90004619c08fd613adf9f4c69bb1ee30dfd2fe2529862b39669c9

# Conflicts:
#	src/main.cpp