[GUI][Trivial] Rewording of Error message while trying to send with the transaction with wallet unlocked for staking only
Not sure if this is good or it needs to be:

> Error: The wallet is unlocked for anonymization and staking only.**\n**Unlock the wallet to send the transaction.
Github-Pull: #1159
Rebased-From: 9253412554562fa0195c3074121f5dd36951d5e9